[__config__]
oldver = "old.json"
newver = "new.json"

[colgrep]
source = "github"
github = "lightonai/next-plaid"
use_latest_release = true
prefix = "v"

[colgrep-bin]
source = "github"
github = "lightonai/next-plaid"
use_latest_release = true
prefix = "v"
